### PR TITLE
moved to a global module, reorganize and added sigterm confirmation

### PR DESCRIPTION
**Pull request by tgsoverly**
Here are some thoughts on organizing this a bit for future testing and development.

1. Added catch/confirm with interrupt sigint
1. Made it a global install so you don't need ./
1. Moved to separate files for easier testing

Still haven't tested the whole thing...

screen shot 2017-12-16 at 10 32 43 am

### CODE REVIEW

**Comment by exsilium** [comment]
Hi! This makes a lot of sense - Thanks and Cheers! 🍻

**Comment by exsilium** [comment]
I'm having issues, the interrupt works nicely but the bypass and firmware updates are lacking the needed references like serialport and xbee_api

**Comment by tgsoverly** [comment]
Oh no!  Yea I still needed to do some stuff. I was putting it up for discussion to see if you liked it. I am sure I missed a reference.

**Comment by tgsoverly** [comment]
Probably needs the imports at the very least.

**Comment by exsilium** [comment]
No problems, reverting, wasn't clear it was still WIP :)

**Comment by exsilium** [comment]
Just open a new pull request and I'll wait for your signal once you're done. :) The breakdown looks good and it will surely be more maintainable that way.

**Comment by tgsoverly** [comment]
@exsilium I realized I currently don't have any good way to test it all.  I have new modules on the way, but can't program anything right now...  Be a couple weeks probably.  I did take a better guess at imports, so it should be pretty close now.

**Pull request merged**
