### PR TITLE
moved to a global module and reorganize

### PR DESCRIPTION
**Pull request by tgsoverly**
** DO NOT MERGE **

Opening a new PR for discussion.

I have been playing around a bit with testing

You can give a see what it does with `npm test`

### CODE REVIEW

**Comment by exsilium** [comment]
Related to #1 , will test this evening and provide further feedback.

**Comment by exsilium** [comment]
1. Bypass technically works 👍 but the `NI` command response is not handled. The upgrade to serialport 6 drops support for the custom parser interface. You should also pump xbee-api to 0.6.0 in that case and use the new stream transformer interface. However, for the simplicity of this restructuring I propose you pull back to serialport 4, so we can test this in detail, merge the changes and then move forward with `serialport 6` and `xbee-api 0.6.0`. How does that sound?

2. Although currently ignored in handle-bypass, the reference to handleExit() is missing. Make it a global in fwup.js ?
3. Firmware update is missing `fs` import. 😁 
4. Firmware update is also missing the reference to handleExit():
`2017-12-18T19:24:27.502Z (node:1998) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: handleExit is not defined`

If you address these, I think we can merge and move on... 💡 ❓ 😄 🍻

**Comment by tgsoverly** [comment]
Will do!  I also got my modules now so I can do some more testing.

**Comment by tgsoverly** [comment]
Okay I think I cleaned up all that stuff.  I added a linter (shrug), can take that out if you don't like it and found a little utility to do the console time stamp too.

**Comment by exsilium** [comment]
Thanks! I'll give it a try later today or tomorrow! :) Cheers!

**Comment by exsilium** [comment]
Just an update that, this task is still in my backlog! Hopefully this weekend will give some opportunity to test and merge this piece of awesomeness! 🙇

**Comment by exsilium** [comment]
Finally had time to test this out, looks good and works good! Thanks @tgsoverly ! 🎉 🎈 Merging!

**Pull request merged**
